import psycopg2
import os
from dotenv import load_dotenv

load_dotenv()

# Connect to PostgreSQL
conn = psycopg2.connect(
    host=os.getenv("DB_HOST"),
    port=os.getenv("DB_PORT"),
    database=os.getenv("DB_NAME"),
    user=os.getenv("DB_USER"),
    password=os.getenv("DB_PASSWORD")
)

cursor = conn.cursor()


# 1. Institutions
cursor.execute("""
CREATE TABLE IF NOT EXISTS institutions (
    institution_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email_domain TEXT,
    address TEXT
)
""")


# 2. Students
cursor.execute("""
CREATE TABLE IF NOT EXISTS students (
    student_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institution_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    roll_number TEXT,
    is_verified INTEGER DEFAULT 0,

    FOREIGN KEY (institution_id)
    REFERENCES institutions(institution_id)
)
""")


# 3. Admins
cursor.execute("""
CREATE TABLE IF NOT EXISTS admins (
    admin_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institution_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,

    FOREIGN KEY (institution_id)
    REFERENCES institutions(institution_id)
)
""")


# 4. Departments
cursor.execute("""
CREATE TABLE IF NOT EXISTS departments (
    department_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institution_id INTEGER NOT NULL,
    department_name TEXT NOT NULL,

    FOREIGN KEY (institution_id)
    REFERENCES institutions(institution_id)
)
""")


# 5. Courses
cursor.execute("""
CREATE TABLE IF NOT EXISTS courses (
    course_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id INTEGER NOT NULL,
    course_code TEXT NOT NULL,
    course_name TEXT NOT NULL,

    FOREIGN KEY (department_id)
    REFERENCES departments(department_id)
)
""")


# 6. Buildings
cursor.execute("""
CREATE TABLE IF NOT EXISTS buildings (
    building_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institution_id INTEGER NOT NULL,
    building_name TEXT NOT NULL,

    FOREIGN KEY (institution_id)
    REFERENCES institutions(institution_id)
)
""")


# 7. Floors
cursor.execute("""
CREATE TABLE IF NOT EXISTS floors (
    floor_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    building_id INTEGER NOT NULL,
    floor_number INTEGER NOT NULL,

    FOREIGN KEY (building_id)
    REFERENCES buildings(building_id)
)
""")


# 8. Rooms
cursor.execute("""
CREATE TABLE IF NOT EXISTS rooms (
    room_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    floor_id INTEGER NOT NULL,
    room_number TEXT NOT NULL,
    room_name TEXT,
    room_type TEXT,

    x_coordinate REAL,
    y_coordinate REAL,
    z_coordinate REAL,

    FOREIGN KEY (floor_id)
    REFERENCES floors(floor_id)
)
""")


# 9. Events
cursor.execute("""
CREATE TABLE IF NOT EXISTS events (
    event_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institution_id INTEGER NOT NULL,
    event_name TEXT NOT NULL,
    event_date TEXT,
    location TEXT,

    FOREIGN KEY (institution_id)
    REFERENCES institutions(institution_id)
)
""")


# 10. Knowledge Documents
cursor.execute("""
CREATE TABLE IF NOT EXISTS knowledge_documents (
    document_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institution_id INTEGER NOT NULL,
    title TEXT NOT NULL,
    file_path TEXT,
    uploaded_at TEXT DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (institution_id)
    REFERENCES institutions(institution_id)
)
""")


# 11. Societies
cursor.execute("""
CREATE TABLE IF NOT EXISTS societies (
    society_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institution_id INTEGER NOT NULL,
    society_name TEXT NOT NULL,
    description TEXT,
    faculty_coordinator TEXT,

    FOREIGN KEY (institution_id)
    REFERENCES institutions(institution_id)
)
""")


# 12. Society Members
cursor.execute("""
CREATE TABLE IF NOT EXISTS society_members (
    membership_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    society_id INTEGER NOT NULL,
    student_id INTEGER NOT NULL,
    role TEXT DEFAULT 'Member',

    FOREIGN KEY (society_id)
    REFERENCES societies(society_id),

    FOREIGN KEY (student_id)
    REFERENCES students(student_id)
)
""")


# 13. Reminders
cursor.execute("""
CREATE TABLE IF NOT EXISTS reminders (
    reminder_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL,
    title TEXT NOT NULL,
    reminder_date TEXT,
    description TEXT,

    FOREIGN KEY (student_id)
    REFERENCES students(student_id)
)
""")


# Save changes
conn.commit()

# Close connection
cursor.close()
conn.close()

print("Athena PostgreSQL database setup completed successfully!")