#!/usr/bin/env python3
"""
Athena DB Setup Script
======================
One-shot script to nuke and rebuild the entire database on a fresh Neon instance.
Run from the project root:  python UCS503P-202627-Athena-Project/DataBase/setup_neon.py

Reads DATABASE_URL (priority) or individual DB_* vars from the root .env file.
"""

import os
import sys
import psycopg2
from dotenv import load_dotenv

# ---------------------------------------------------------------------------
# 1. Connect
# ---------------------------------------------------------------------------
load_dotenv()

database_url = os.getenv("DATABASE_URL")

if database_url:
    conn = psycopg2.connect(database_url)
    print(f"✓ Connected via DATABASE_URL")
else:
    host = os.getenv("DB_HOST")
    conn = psycopg2.connect(
        host=host,
        port=os.getenv("DB_PORT"),
        database=os.getenv("DB_NAME"),
        user=os.getenv("DB_USER"),
        password=os.getenv("DB_PASSWORD"),
        sslmode="require",
    )
    print(f"✓ Connected via DB_* vars → {host}")

conn.autocommit = False
cursor = conn.cursor()

# ---------------------------------------------------------------------------
# 2. Drop all existing tables
# ---------------------------------------------------------------------------
print("\n— Dropping all existing tables …")

cursor.execute("""
    SELECT tablename FROM pg_tables WHERE schemaname = 'public'
""")
tables = [row[0] for row in cursor.fetchall()]

if tables:
    # CASCADE handles foreign-key dependencies
    cursor.execute("DROP TABLE IF EXISTS " + ", ".join(f'"{t}"' for t in tables) + " CASCADE")
    conn.commit()
    print(f"  Dropped {len(tables)} table(s): {', '.join(tables)}")
else:
    print("  No tables to drop.")

# ---------------------------------------------------------------------------
# 3. Create all 13 Athena tables
# ---------------------------------------------------------------------------
print("\n— Creating tables …")

TABLE_SQL = [
    # 1. Institutions
    """
    CREATE TABLE institutions (
        institution_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        email_domain TEXT,
        address TEXT
    )
    """,
    # 2. Students
    """
    CREATE TABLE students (
        student_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        institution_id INTEGER NOT NULL,
        name TEXT NOT NULL,
        email TEXT UNIQUE NOT NULL,
        phone TEXT,
        branch TEXT,
        roll_number TEXT,
        is_verified BOOLEAN DEFAULT FALSE,
        FOREIGN KEY (institution_id) REFERENCES institutions(institution_id)
    )
    """,
    # 3. Admins
    """
    CREATE TABLE admins (
        admin_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        institution_id INTEGER NOT NULL,
        name TEXT NOT NULL,
        email TEXT UNIQUE NOT NULL,
        FOREIGN KEY (institution_id) REFERENCES institutions(institution_id)
    )
    """,
    # 4. Departments
    """
    CREATE TABLE departments (
        department_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        institution_id INTEGER NOT NULL,
        department_name TEXT NOT NULL,
        FOREIGN KEY (institution_id) REFERENCES institutions(institution_id)
    )
    """,
    # 5. Courses
    """
    CREATE TABLE courses (
        course_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        department_id INTEGER NOT NULL,
        course_code TEXT NOT NULL,
        course_name TEXT NOT NULL,
        FOREIGN KEY (department_id) REFERENCES departments(department_id)
    )
    """,
    # 6. Buildings
    """
    CREATE TABLE buildings (
        building_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        institution_id INTEGER NOT NULL,
        building_name TEXT NOT NULL,
        FOREIGN KEY (institution_id) REFERENCES institutions(institution_id)
    )
    """,
    # 7. Floors
    """
    CREATE TABLE floors (
        floor_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        building_id INTEGER NOT NULL,
        floor_number INTEGER NOT NULL,
        FOREIGN KEY (building_id) REFERENCES buildings(building_id)
    )
    """,
    # 8. Rooms
    """
    CREATE TABLE rooms (
        room_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        floor_id INTEGER NOT NULL,
        room_number TEXT NOT NULL,
        room_name TEXT,
        room_type TEXT,
        x_coordinate REAL,
        y_coordinate REAL,
        z_coordinate REAL,
        FOREIGN KEY (floor_id) REFERENCES floors(floor_id)
    )
    """,
    # 9. Events
    """
    CREATE TABLE events (
        event_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        institution_id INTEGER NOT NULL,
        event_name TEXT NOT NULL,
        event_date TEXT,
        location TEXT,
        FOREIGN KEY (institution_id) REFERENCES institutions(institution_id)
    )
    """,
    # 10. Knowledge Documents
    """
    CREATE TABLE knowledge_documents (
        document_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        institution_id INTEGER NOT NULL,
        title TEXT NOT NULL,
        file_path TEXT,
        uploaded_at TEXT DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (institution_id) REFERENCES institutions(institution_id)
    )
    """,
    # 11. Societies
    """
    CREATE TABLE societies (
        society_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        institution_id INTEGER NOT NULL,
        society_name TEXT NOT NULL,
        description TEXT,
        faculty_coordinator TEXT,
        FOREIGN KEY (institution_id) REFERENCES institutions(institution_id)
    )
    """,
    # 12. Society Members
    """
    CREATE TABLE society_members (
        membership_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        society_id INTEGER NOT NULL,
        student_id INTEGER NOT NULL,
        role TEXT DEFAULT 'Member',
        FOREIGN KEY (society_id) REFERENCES societies(society_id),
        FOREIGN KEY (student_id) REFERENCES students(student_id)
    )
    """,
    # 13. Reminders
    """
    CREATE TABLE reminders (
        reminder_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        student_id INTEGER NOT NULL,
        title TEXT NOT NULL,
        reminder_date TEXT,
        description TEXT,
        FOREIGN KEY (student_id) REFERENCES students(student_id)
    )
    """,
]

for sql in TABLE_SQL:
    cursor.execute(sql)

conn.commit()
print(f"  Created {len(TABLE_SQL)} tables.")

# ---------------------------------------------------------------------------
# 4. Seed institution
# ---------------------------------------------------------------------------
print("\n— Seeding institution …")

cursor.execute("""
    INSERT INTO institutions (institution_id, name, email_domain, address)
    VALUES (1, 'Thapar Institute of Engineering & Technology', 'thapar.edu', 'Patiala, Punjab, India')
    ON CONFLICT (institution_id) DO NOTHING
""")
conn.commit()
print("  ✓ institution_id = 1 ready.")

# ---------------------------------------------------------------------------
# 5. Import Students.sql
# ---------------------------------------------------------------------------
print("\n— Importing Students.sql …")

# Resolve path relative to this script's location
script_dir = os.path.dirname(os.path.abspath(__file__))
# Students.sql lives at the project root (two levels up from DataBase/)
students_sql_path = os.path.join(script_dir, "..", "..", "Students.sql")
students_sql_path = os.path.normpath(students_sql_path)

if not os.path.exists(students_sql_path):
    # Fallback: check CWD (if run from project root)
    students_sql_path = os.path.join(os.getcwd(), "Students.sql")

if os.path.exists(students_sql_path):
    with open(students_sql_path, "r", encoding="utf-8") as f:
        sql = f.read()
    cursor.execute(sql)
    conn.commit()

    cursor.execute("SELECT COUNT(*) FROM students")
    count = cursor.fetchone()[0]
    print(f"  ✓ Imported {count} students.")
else:
    print(f"  ⚠ Students.sql not found (looked at {students_sql_path}). Skipping.")

# ---------------------------------------------------------------------------
# 6. Reset identity sequences for tables with explicit IDs
# ---------------------------------------------------------------------------
print("\n— Resetting identity sequences …")

TABLES_WITH_IDENTITY = [
    "institutions", "students", "admins", "departments", "courses",
    "buildings", "floors", "rooms", "events", "knowledge_documents",
    "societies", "society_members", "reminders",
]

for table in TABLES_WITH_IDENTITY:
    cursor.execute(f"SELECT COUNT(*) FROM {table}")
    if cursor.fetchone()[0] > 0:
        # Find the PK column name (first column of the primary key)
        cursor.execute("""
            SELECT a.attname
            FROM pg_index i
            JOIN pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = ANY(i.indkey)
            WHERE i.indrelid = %s::regclass AND i.indisprimary
        """, (table,))
        pk_col = cursor.fetchone()[0]

        cursor.execute(f"""
            SELECT setval(
                pg_get_serial_sequence('{table}', '{pk_col}'),
                (SELECT MAX({pk_col}) FROM {table})
            )
        """)

conn.commit()
print("  ✓ All sequences synced.")

# ---------------------------------------------------------------------------
# 7. Insert demo data (building, floor, room, department, event)
# ---------------------------------------------------------------------------
print("\n— Inserting demo data …")

cursor.execute("""
    INSERT INTO departments (institution_id, department_name)
    VALUES (1, 'Computer Science')
    ON CONFLICT DO NOTHING
""")

cursor.execute("""
    INSERT INTO buildings (institution_id, building_name)
    VALUES (1, 'Computer Science Block')
    ON CONFLICT DO NOTHING
    RETURNING building_id
""")
row = cursor.fetchone()
if row:
    building_id = row[0]

    cursor.execute("""
        INSERT INTO floors (building_id, floor_number) VALUES (%s, 2)
        RETURNING floor_id
    """, (building_id,))
    floor_id = cursor.fetchone()[0]

    cursor.execute("""
        INSERT INTO rooms (floor_id, room_number, room_name, room_type,
                           x_coordinate, y_coordinate, z_coordinate)
        VALUES (%s, '204', 'AI Lab', 'Laboratory', 12.5, 8.2, 3.0)
    """, (floor_id,))

cursor.execute("""
    INSERT INTO events (institution_id, event_name, event_date, location)
    VALUES (1, 'Tech Fest', '2026-09-10', 'Main Auditorium')
    ON CONFLICT DO NOTHING
""")

conn.commit()
print("  ✓ Demo building / floor / room / event inserted.")

# ---------------------------------------------------------------------------
# 8. Final summary
# ---------------------------------------------------------------------------
print("\n— Final summary:")

for table in TABLES_WITH_IDENTITY:
    cursor.execute(f"SELECT COUNT(*) FROM {table}")
    count = cursor.fetchone()[0]
    if count > 0:
        print(f"  {table:25s} → {count} rows")

# ---------------------------------------------------------------------------
# Cleanup
# ---------------------------------------------------------------------------
cursor.close()
conn.close()
print("\n✅ Neon DB setup complete!")
